# Generated by Django 4.2.16 on 2026-04-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='slug',
            field=models.SlugField(help_text='Identificador URL-friendly', max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='max_transactions_mo',
            field=models.IntegerField(default=500, help_text='Transactions per month'),
        ),
    ]
