# Generated by Django 4.2.16 on 2026-04-14 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_auditlog_audit_ct_obj_ts_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0002_add_accion_sugerida_new_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertlog',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertlog_acknowledged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Sucursal involucrada (NULL = sistema global).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_logs', to='users.branch'),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Contexto adicional: deltas, valores, umbrales, etc.'),
        ),
        migrations.AlterField(
            model_name='alertlog',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertlog_triggered', to=settings.AUTH_USER_MODEL),
        ),
    ]
