# Generated by Django 4.2.16 on 2026-03-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashTransactionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('report_date', models.DateField()),
                ('amount_usd_equiv', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency_code', models.CharField(max_length=5)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('exchange_rate_usd', models.DecimalField(decimal_places=6, max_digits=10)),
                ('customer_full_name', models.CharField(max_length=200)),
                ('customer_document_type', models.CharField(max_length=20)),
                ('customer_document_num', models.CharField(max_length=50)),
                ('customer_nationality', models.CharField(default='Boliviana', max_length=50)),
                ('customer_is_pep', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('SUBMITTED', 'Enviado a ASFI'), ('ACCEPTED', 'Aceptado'), ('REJECTED', 'Rechazado')], default='PENDING', max_length=15)),
                ('asfi_reference', models.CharField(blank=True, max_length=50)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RTE — Transacción en Efectivo',
                'verbose_name_plural': 'RTE — Transacciones en Efectivo',
                'db_table': 'reports_rte',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_date', models.DateField()),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('CLOSED', 'Cerrado'), ('LOCKED', 'Bloqueado')], default='OPEN', max_length=10)),
                ('total_transactions', models.IntegerField(default=0)),
                ('total_buy_bob', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_sell_bob', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_profit_bob', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('rte_count', models.IntegerField(default=0)),
                ('opening_balance_bob', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('closing_balance_bob', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('excel_file', models.CharField(blank=True, max_length=500)),
                ('pdf_file', models.CharField(blank=True, max_length=500)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'reports_daily_log',
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('RTE_MONTHLY', 'RTE Mensual ASFI'), ('ROUE_REPORT', 'ROUE ASFI'), ('PEP_LIST', 'Listado PEP ASFI'), ('DAILY_LOG', 'Libro Diario ASFI'), ('PNL_DAILY', 'P&G Diario'), ('PNL_MONTHLY', 'P&G Mensual'), ('PROFITABILITY', 'Rentabilidad Divisa/Sucursal'), ('CASHFLOW', 'Proyección Flujo de Caja'), ('COMPARATIVE', 'Comparativo Período Anterior'), ('CLIENT_RANKING', 'Ranking de Clientes')], max_length=30)),
                ('format', models.CharField(choices=[('EXCEL', 'Excel'), ('PDF', 'PDF')], max_length=10)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('file_path', models.CharField(max_length=500)),
                ('file_size_kb', models.IntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'reports_generated',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PEPRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('since_date', models.DateField()),
                ('until_date', models.DateField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto')], default='HIGH', max_length=10)),
                ('enhanced_dd', models.BooleanField(default=True)),
                ('review_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reports_pep',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_number', models.CharField(editable=False, max_length=30, unique=True)),
                ('report_type', models.CharField(choices=[('UNUSUAL', 'Operación Inusual'), ('SUSPICIOUS', 'Operación Sospechosa')], max_length=15)),
                ('risk_level', models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto'), ('CRITICAL', 'Crítico')], default='MEDIUM', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('REVIEW', 'En Revisión'), ('SUBMITTED', 'Enviado'), ('CLOSED', 'Cerrado')], default='DRAFT', max_length=15)),
                ('description', models.TextField()),
                ('indicators', models.JSONField(default=list)),
                ('amount_involved', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency_involved', models.CharField(default='USD', max_length=5)),
                ('asfi_reference', models.CharField(blank=True, max_length=50)),
                ('internal_notes', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'reports_roue',
                'ordering': ['-detected_at'],
            },
        ),
    ]
