# Generated by Django 4.2.16 on 2026-03-25 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('transactions', '0001_initial'),
        ('reports', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='detected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sar_detected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sar_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sar_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspiciousactivityreport',
            name='transactions',
            field=models.ManyToManyField(blank=True, related_name='sar_reports', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='pepregistry',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pep_registry', to='transactions.customer'),
        ),
        migrations.AddField(
            model_name='pepregistry',
            name='registered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pep_registered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedreport',
            name='generated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports_generated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyoperationlog',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_logs', to='users.branch'),
        ),
        migrations.AddField(
            model_name='dailyoperationlog',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashtransactionreport',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rte_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashtransactionreport',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='rte_report', to='transactions.transaction'),
        ),
        migrations.AddIndex(
            model_name='suspiciousactivityreport',
            index=models.Index(fields=['status', 'risk_level'], name='reports_rou_status_c3e712_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyoperationlog',
            unique_together={('log_date', 'branch')},
        ),
        migrations.AddIndex(
            model_name='cashtransactionreport',
            index=models.Index(fields=['report_date'], name='reports_rte_report__03b4f6_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransactionreport',
            index=models.Index(fields=['status'], name='reports_rte_status_2668ff_idx'),
        ),
        migrations.AddIndex(
            model_name='cashtransactionreport',
            index=models.Index(fields=['customer_document_num'], name='reports_rte_custome_4569a1_idx'),
        ),
    ]
