# Generated by Django 4.2.16 on 2026-07-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedreport',
            name='format',
            field=models.CharField(choices=[('EXCEL', 'Excel'), ('PDF', 'PDF'), ('CSV', 'CSV')], max_length=10),
        ),
    ]
