# Generated by Django 4.2.30 on 2026-07-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MacroIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(choices=[('inflacion_yoy', 'Inflación anual % (WB FP.CPI.TOTL.ZG)'), ('reservas_usd', 'Reservas internacionales US$ (WB FI.RES.TOTL.CD)'), ('pib_crecimiento', 'Crecimiento PIB % (WB NY.GDP.MKTP.KD.ZG)'), ('deuda_externa_usd', 'Deuda externa US$ (WB DT.DOD.DECT.CD)'), ('tasa_interes_activa', 'Tasa de interés activa % (WB FR.INR.LEND)'), ('tc_oficial_promedio', 'TC oficial promedio anual (WB PA.NUS.FCRF)'), ('usd_internacional', 'USD/BOB internacional (open.er-api.com)'), ('brecha_oficial_pct', 'Brecha oficial↔paralelo % (interna)')], db_index=True, max_length=32)),
                ('date', models.DateField(db_index=True)),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('unit', models.CharField(blank=True, default='', max_length=20)),
                ('source', models.CharField(blank=True, default='', max_length=60)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Indicador Macro',
                'verbose_name_plural': 'Indicadores Macro',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['series', '-date'], name='macro_series_date_idx')],
                'unique_together': {('series', 'date')},
            },
        ),
    ]
