# Generated by Django 4.2.30 on 2026-07-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macroindicator',
            name='series',
            field=models.CharField(choices=[('inflacion_yoy', 'Inflación anual % (WB FP.CPI.TOTL.ZG)'), ('reservas_usd', 'Reservas internacionales US$ (WB FI.RES.TOTL.CD)'), ('pib_crecimiento', 'Crecimiento PIB % (WB NY.GDP.MKTP.KD.ZG)'), ('deuda_externa_usd', 'Deuda externa US$ (WB DT.DOD.DECT.CD)'), ('tasa_interes_activa', 'Tasa de interés activa % (WB FR.INR.LEND)'), ('tc_oficial_promedio', 'TC oficial promedio anual (WB PA.NUS.FCRF)'), ('usd_internacional', 'USD/BOB internacional (open.er-api.com)'), ('brecha_oficial_pct', 'Brecha oficial↔paralelo % (interna)'), ('sentimiento_dolar', 'Sentimiento noticias dólar [-1,1] (RSS)')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('url', models.URLField(max_length=600, unique=True)),
                ('source', models.CharField(blank=True, default='', max_length=120)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('sentiment', models.FloatField(default=0.0)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('query', models.CharField(blank=True, default='', max_length=80)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['-published_at'], name='news_pub_idx'), models.Index(fields=['sentiment', '-published_at'], name='news_sent_idx')],
            },
        ),
    ]
