# Generated by Django 4.2.30 on 2026-07-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macro', '0002_alter_macroindicator_series_newsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macroindicator',
            name='series',
            field=models.CharField(choices=[('inflacion_yoy', 'Inflación anual % (WB FP.CPI.TOTL.ZG)'), ('reservas_usd', 'Reservas internacionales US$ (WB FI.RES.TOTL.CD)'), ('pib_crecimiento', 'Crecimiento PIB % (WB NY.GDP.MKTP.KD.ZG)'), ('deuda_externa_usd', 'Deuda externa US$ (WB DT.DOD.DECT.CD)'), ('tasa_interes_activa', 'Tasa de interés activa % (WB FR.INR.LEND)'), ('tc_oficial_promedio', 'TC oficial promedio anual (WB PA.NUS.FCRF)'), ('usd_internacional', 'USD/BOB internacional (open.er-api.com)'), ('tc_oficial_diario', 'TC oficial BCB diario (dolarapi/currency-api)'), ('brecha_oficial_pct', 'Brecha oficial↔paralelo % (interna)'), ('sentimiento_dolar', 'Sentimiento noticias dólar [-1,1] (RSS)')], db_index=True, max_length=32),
        ),
    ]
