# Generated by Django 4.2.16 on 2026-04-08 23:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_profit_ledger_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exposuresnapshot',
            new_name='analytics_e_branch__379a28_idx',
            old_name='analytics_exp_branch_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='exposuresnapshot',
            new_name='analytics_e_currenc_7acdd9_idx',
            old_name='analytics_exp_currency_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='exposuresnapshot',
            new_name='analytics_e_alert_l_885440_idx',
            old_name='analytics_exp_alert_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='pnldailysnapshot',
            new_name='analytics_p_branch__2e740f_idx',
            old_name='analytics_pnl_branch_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='spreadsnapshot',
            new_name='analytics_s_currenc_b3b9d8_idx',
            old_name='analytics_spread_currency_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='spreadsnapshot',
            new_name='analytics_s_market__0170a2_idx',
            old_name='analytics_spread_market_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='spreadsnapshot',
            new_name='analytics_s_currenc_6734c0_idx',
            old_name='analytics_spread_curr_mkt_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionprofitledger',
            new_name='analytics_p_currenc_7917ea_idx',
            old_name='analytics_profit_currency_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionprofitledger',
            new_name='analytics_p_branch__83ae62_idx',
            old_name='analytics_profit_branch_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionprofitledger',
            new_name='analytics_p_fecha_e5ca83_idx',
            old_name='analytics_profit_fecha_type_idx',
        ),
        migrations.AlterField(
            model_name='exposuresnapshot',
            name='exposure_bob',
            field=models.DecimalField(decimal_places=2, help_text='Valor de mercado total en BOB: stock × sell_rate_unit', max_digits=18),
        ),
        migrations.AlterField(
            model_name='exposuresnapshot',
            name='pct_of_capital',
            field=models.DecimalField(decimal_places=4, help_text='% del capital total representado por esta divisa', max_digits=7),
        ),
        migrations.AlterField(
            model_name='exposuresnapshot',
            name='sell_rate_lote',
            field=models.DecimalField(decimal_places=4, help_text='Tasa de venta por lote (cotizada, antes de normalizar)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='exposuresnapshot',
            name='sell_rate_unit',
            field=models.DecimalField(decimal_places=4, help_text='Tasa de venta por UNIDAD (normalizada por scale_factor)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='exposuresnapshot',
            name='stock_units',
            field=models.DecimalField(decimal_places=4, help_text='Stock en unidades de la divisa (en lotes para CLP/ARS)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='exposuresnapshot',
            name='unrealized_pnl_bob',
            field=models.DecimalField(decimal_places=2, help_text='Ganancia/pérdida latente: (sell_rate_unit - wac) × stock_units. Positivo: vendería con ganancia. Negativo: vendería con pérdida.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='exposuresnapshot',
            name='wac',
            field=models.DecimalField(decimal_places=4, help_text='Costo promedio ponderado actual (BOB por lote)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='pnldailysnapshot',
            name='costo_ventas_bob',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Costo WAC de las divisas vendidas', max_digits=18),
        ),
        migrations.AlterField(
            model_name='pnldailysnapshot',
            name='ganancia_bruta_bob',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='ingreso_ventas - costo_ventas', max_digits=18),
        ),
        migrations.AlterField(
            model_name='pnldailysnapshot',
            name='ganancia_neta_bob',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='ganancia_bruta - gastos_operativos', max_digits=18),
        ),
        migrations.AlterField(
            model_name='pnldailysnapshot',
            name='gastos_operativos_bob',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Suma de Gastos.monto_bob del día', max_digits=18),
        ),
        migrations.AlterField(
            model_name='pnldailysnapshot',
            name='ingreso_ventas_bob',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='BOB recibidos por ventas de divisa', max_digits=18),
        ),
        migrations.AlterField(
            model_name='pnldailysnapshot',
            name='inversion_compras_bob',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='BOB pagados al comprar divisa (inversión en stock)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='pnldailysnapshot',
            name='margen_neto_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='ganancia_neta / ingreso_ventas × 100', max_digits=8),
        ),
        migrations.AlterField(
            model_name='spreadsnapshot',
            name='market_type',
            field=models.CharField(help_text='Tipo de mercado: official, bcb, paralelo_digital, etc.', max_length=30),
        ),
        migrations.AlterField(
            model_name='spreadsnapshot',
            name='official_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa oficial BCB del momento (para calcular prima)', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='spreadsnapshot',
            name='prima_oficial_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Prima sobre tasa oficial: (sell_rate / official_rate - 1) × 100', max_digits=8),
        ),
        migrations.AlterField(
            model_name='spreadsnapshot',
            name='spread_bob',
            field=models.DecimalField(decimal_places=4, help_text='Spread en BOB: sell_rate - buy_rate', max_digits=10),
        ),
        migrations.AlterField(
            model_name='spreadsnapshot',
            name='spread_pct',
            field=models.DecimalField(decimal_places=4, help_text='Spread porcentual: spread / buy_rate × 100', max_digits=8),
        ),
        migrations.AlterField(
            model_name='transactionprofitledger',
            name='amount_bob',
            field=models.DecimalField(decimal_places=2, help_text='Bolivianos involucrados en la transacción (amount_from.amount_to)', max_digits=18),
        ),
        migrations.AlterField(
            model_name='transactionprofitledger',
            name='amount_foreign',
            field=models.DecimalField(decimal_places=4, help_text='Monto en divisa extranjera intercambiado', max_digits=18),
        ),
        migrations.AlterField(
            model_name='transactionprofitledger',
            name='cost_bob',
            field=models.DecimalField(decimal_places=2, help_text='Costo contable en BOB de la divisa involucrada. SELL: amount_foreign × wac_at_transaction. BUY: amount_foreign × exchange_rate (= lo que pagamos).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='transactionprofitledger',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=4, help_text='Tipo de cambio usado en la transacción (BOB por unidad)', max_digits=14),
        ),
        migrations.AlterField(
            model_name='transactionprofitledger',
            name='profit_bob',
            field=models.DecimalField(decimal_places=2, help_text='Ganancia/pérdida neta en BOB. SELL: amount_bob - cost_bob = (sell_rate - wac) × amount_foreign. BUY: siempre 0 (la ganancia se realiza al vender).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='transactionprofitledger',
            name='profit_pct',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Margen sobre el costo: profit_bob / cost_bob × 100', max_digits=8),
        ),
        migrations.AlterField(
            model_name='transactionprofitledger',
            name='spread_bob',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Spread por unidad: sell_rate - wac (o 0 para BUY)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transactionprofitledger',
            name='wac_after_transaction',
            field=models.DecimalField(decimal_places=4, help_text='WAC del inventario DESPUÉS de la transacción. Para BUY: nuevo WAC ponderado. Para SELL: igual al anterior (WAC no cambia al vender).', max_digits=14),
        ),
        migrations.AlterField(
            model_name='transactionprofitledger',
            name='wac_at_transaction',
            field=models.DecimalField(decimal_places=4, help_text='WAC del inventario al momento de la transacción. Para BUY: WAC ANTES de la compra. Para SELL: WAC ANTES de la venta (= costo unitario de lo vendido).', max_digits=14),
        ),
    ]
