# Generated by Django 4.2.16 on 2026-04-13 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_add_capital_anomaly_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='capitalanomalylog',
            new_name='analytics_a_severit_bbd1c7_idx',
            old_name='analytics_anomaly_severity_idx',
        ),
        migrations.RenameIndex(
            model_name='capitalanomalylog',
            new_name='analytics_a_rule_1043a2_idx',
            old_name='analytics_anomaly_rule_idx',
        ),
        migrations.RenameIndex(
            model_name='capitalanomalylog',
            new_name='analytics_a_branch__0475e6_idx',
            old_name='analytics_anomaly_branch_idx',
        ),
        migrations.RenameIndex(
            model_name='capitalanomalylog',
            new_name='analytics_a_resolve_92d198_idx',
            old_name='analytics_anomaly_resolved_idx',
        ),
    ]
