# Generated by Django 4.2.16 on 2026-04-13 13:40

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_auditlog_audit_ct_obj_ts_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0005_rename_analytics_anomaly_severity_idx_analytics_a_severit_bbd1c7_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('currency', models.CharField(db_index=True, max_length=5)),
                ('from_cache', models.BooleanField(default=False, help_text='True si la respuesta fue servida desde caché Redis.')),
                ('decision', models.CharField(choices=[('COMPRAR', 'Comprar'), ('VENDER', 'Vender'), ('ESPERAR', 'Esperar'), ('SIN_DATOS', 'Sin datos')], db_index=True, max_length=10)),
                ('confianza', models.IntegerField(help_text='Confianza 0–100')),
                ('riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto'), ('N/A', 'N/A')], max_length=8)),
                ('precio_compra', models.DecimalField(decimal_places=4, help_text='Precio de compra recomendado al momento de la decisión', max_digits=14)),
                ('precio_venta', models.DecimalField(decimal_places=4, help_text='Precio de venta recomendado al momento de la decisión', max_digits=14)),
                ('motivo', models.TextField()),
                ('score_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('input_snapshot', models.JSONField(default=dict, help_text='Datos de entrada usados: tasas, spread, stock, volumen, tendencia, competencia, binance al momento de la decisión.')),
                ('full_result', models.JSONField(default=dict, help_text='Resultado completo de DecisionEngine.evaluar() — para trazabilidad.')),
                ('outcome_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Tasa de venta real EVAL_HOURS horas después de la decisión.', max_digits=14, null=True)),
                ('outcome_delta_pct', models.DecimalField(blank=True, decimal_places=4, help_text='% de cambio de la tasa entre la decision y el outcome.', max_digits=8, null=True)),
                ('decision_was_correct', models.BooleanField(help_text='¿La dirección del mercado coincidió con la decisión?', null=True)),
                ('outcome_evaluated_at', models.DateTimeField(blank=True, help_text='Momento en que se evaluó el outcome.', null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to='users.branch')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Decisión Registrada',
                'verbose_name_plural': 'Decisiones Registradas',
                'db_table': 'analytics_decision_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['currency', '-timestamp'], name='analytics_d_currenc_a282dd_idx'), models.Index(fields=['decision', '-timestamp'], name='analytics_d_decisio_76affb_idx'), models.Index(fields=['branch', '-timestamp'], name='analytics_d_branch__145b7b_idx'), models.Index(fields=['decision_was_correct', '-timestamp'], name='analytics_d_decisio_419548_idx')],
            },
        ),
    ]
