# Generated by Django 4.2.30 on 2026-07-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_populate_celery_beat_schedules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposuresnapshot',
            name='currency_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='spreadsnapshot',
            name='currency_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionprofitledger',
            name='currency_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
