# Generated by Django 4.2.16 on 2026-04-12 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_remove_auditlog_audit_ct_obj_ts_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Momento exacto en que se capturó el estado.')),
                ('module', models.CharField(choices=[('capital', 'Capital / Caja'), ('forex', 'Transacción Forex'), ('tarjetas', 'Tarjetas Prepago'), ('gastos', 'Gasto Operativo'), ('caja_bob', 'Caja BOB'), ('inventory', 'Inventario'), ('manual', 'Manual / On-demand'), ('system', 'Sistema / Cierre de día')], db_index=True, help_text='Módulo del sistema que originó el snapshot.', max_length=20)),
                ('action', models.CharField(choices=[('create', 'Creación'), ('update', 'Actualización'), ('delete', 'Eliminación'), ('transaction', 'Transacción completada'), ('apertura', 'Apertura de día'), ('cierre', 'Cierre de día'), ('on_demand', 'Snapshot on-demand')], help_text='Tipo de acción que desencadenó el snapshot.', max_length=20)),
                ('data_json', models.JSONField(help_text='Estado completo del sistema en el momento del snapshot. Estructura: {capital, caja_bob, divisas, tarjetas}.')),
                ('metadata_json', models.JSONField(blank=True, default=dict, help_text='Contexto adicional: número de transacción, montos involucrados, sucursal, etc.')),
                ('checksum', models.CharField(editable=False, help_text='SHA-256 de data_json (sort_keys=True). Para verificar integridad.', max_length=64)),
                ('branch', models.ForeignKey(blank=True, help_text='Sucursal de contexto (NULL = todas las sucursales).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_snapshots', to='users.branch')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que desencadenó el cambio.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot del Sistema',
                'verbose_name_plural': 'Snapshots del Sistema',
                'db_table': 'snapshots_system',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='snapshots_s_timesta_cce896_idx'), models.Index(fields=['module', '-timestamp'], name='snapshots_s_module_f14036_idx'), models.Index(fields=['branch', '-timestamp'], name='snapshots_s_branch__522f30_idx'), models.Index(fields=['user', '-timestamp'], name='snapshots_s_user_id_5f6391_idx')],
            },
        ),
    ]
