# Generated by Django 4.2.16 on 2026-04-07 23:50

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_branch_options_alter_user_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('categoria', models.CharField(choices=[('ALQUILER', 'Alquiler'), ('SERVICIOS', 'Servicios básicos'), ('SUELDOS', 'Sueldos y salarios'), ('COMISIONES', 'Comisiones'), ('PUBLICIDAD', 'Publicidad y marketing'), ('IMPUESTOS', 'Impuestos y tasas'), ('SUMINISTROS', 'Suministros y materiales'), ('MANTENIMIENTO', 'Mantenimiento'), ('TRANSPORTE', 'Transporte y logística'), ('BANCO', 'Comisiones bancarias'), ('OTROS', 'Otros gastos')], max_length=20)),
                ('descripcion', models.CharField(max_length=300)),
                ('monto_bob', models.DecimalField(decimal_places=2, help_text='Monto del gasto en BOB', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('QR', 'QR / Billetera digital'), ('TRANSFER', 'Transferencia bancaria'), ('TARJETA', 'Tarjeta de débito/crédito')], default='EFECTIVO', max_length=10)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('nro_factura', models.CharField(blank=True, max_length=50)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='users.branch')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'db_table': 'capital_gasto',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['-fecha'], name='capital_gas_fecha_291990_idx'), models.Index(fields=['categoria', '-fecha'], name='capital_gas_categor_6ce157_idx'), models.Index(fields=['branch', '-fecha'], name='capital_gas_branch__3c74d0_idx')],
            },
        ),
        migrations.CreateModel(
            name='CapitalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('efectivo_bob', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('qr_bob', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Saldo en billeteras QR / cuentas digitales', max_digits=18)),
                ('divisas_bob', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Valor de las divisas al TC de venta', max_digits=18)),
                ('tarjetas_bob', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Valor inventario tarjetas al precio de venta prom', max_digits=18)),
                ('pasivos_bob', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Deudas / créditos a pagar', max_digits=18)),
                ('total_bob', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='efectivo + qr + divisas + tarjetas - pasivos', max_digits=18)),
                ('detalle_divisas', models.JSONField(default=dict, help_text='Desglose por divisa')),
                ('detalle_tarjetas', models.JSONField(default=dict, help_text='Desglose por tipo de tarjeta')),
                ('tipo', models.CharField(choices=[('CIERRE', 'Cierre de día'), ('MANUAL', 'Manual / Ad-hoc'), ('APERTURA', 'Apertura de día')], default='MANUAL', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_snapshots', to='users.branch')),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots_capital', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot de Capital',
                'verbose_name_plural': 'Snapshots de Capital',
                'db_table': 'capital_snapshot',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['-fecha', 'branch'], name='capital_sna_fecha_bd1cc4_idx')],
            },
        ),
    ]
