# Generated by Django 4.2.16 on 2026-04-08 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0002_capital_manual_entry'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='capitalmanualentry',
            new_name='capital_man_branch__84cf48_idx',
            old_name='capital_man_branch_fecha_idx',
        ),
    ]
