# Generated by Django 4.2.16 on 2026-04-08 13:09

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_branch_options_alter_user_options'),
        ('capital', '0003_rename_capital_man_branch_fecha_idx_capital_man_branch__84cf48_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalComposicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('fuertes', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Billetes de 200, 100, 50 BOB (denominación alta)', max_digits=15)),
                ('caja_chica', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Billetes de 20, 10 BOB', max_digits=15)),
                ('monedas', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Monedas de 5, 2, 1, 0.50, 0.20, 0.10 BOB', max_digits=15)),
                ('rotos', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Billetes dañados, rasgados o muy usados (se aceptan al 100%)', max_digits=15)),
                ('sueltos', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Billetes sueltos sin clasificar', max_digits=15)),
                ('qr_transferencias', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Saldo en billeteras QR y cuentas de transferencia', max_digits=15)),
                ('tarjetas_telefonicas', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Valor en BOB del stock de tarjetas telefónicas en caja', max_digits=15)),
                ('pasivos', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Deudas con acreedores / obligaciones a pagar', max_digits=15)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_composiciones', to='users.branch')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capital_composiciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Composición de Capital',
                'verbose_name_plural': 'Composiciones de Capital',
                'db_table': 'capital_composicion',
                'ordering': ['-fecha', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CapitalComposicionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_prev', models.JSONField(help_text='Estado previo completo {fuertes, caja_chica, ...}')),
                ('snapshot_new', models.JSONField(help_text='Estado nuevo completo {fuertes, caja_chica, ...}')),
                ('motivo', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('composicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='capital.capitalcomposicion')),
                ('modificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial Composición',
                'verbose_name_plural': 'Historial Composiciones',
                'db_table': 'capital_composicion_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='capitalcomposicion',
            index=models.Index(fields=['branch', '-fecha'], name='capital_com_branch__a235ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='capitalcomposicion',
            unique_together={('branch', 'fecha')},
        ),
    ]
