# Generated by Django 4.2.16 on 2026-04-08 13:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0005_add_cashflowlog'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashflowlog',
            new_name='capital_cas_branch__153b0d_idx',
            old_name='capital_cashflow_branch_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='cashflowlog',
            new_name='capital_cas_transac_ea25b7_idx',
            old_name='capital_cashflow_tx_idx',
        ),
        migrations.RenameIndex(
            model_name='cashflowlog',
            new_name='capital_cas_tipo_864bf6_idx',
            old_name='capital_cashflow_tipo_fecha_idx',
        ),
        migrations.AlterField(
            model_name='cashflowlog',
            name='campo_afectado',
            field=models.CharField(help_text='Campo de CapitalComposicion modificado: "fuertes", "qr_transferencias", etc.', max_length=30),
        ),
        migrations.AlterField(
            model_name='cashflowlog',
            name='concepto',
            field=models.CharField(help_text='Descripción legible: "COMPRA USD × 100", "REVERSA VENTA EUR × 50", etc.', max_length=300),
        ),
        migrations.AlterField(
            model_name='cashflowlog',
            name='monto_bob',
            field=models.DecimalField(decimal_places=2, help_text='Monto absoluto en BOB (siempre positivo; tipo indica dirección)', max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
