# Generated by Django 4.2.16 on 2026-04-12 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_auditlog_audit_ct_obj_ts_idx_and_more'),
        ('capital', '0007_add_cashbob'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cashbob',
            name='capital_cashbob_branch_fecha_uniq',
        ),
        migrations.RenameIndex(
            model_name='cashbob',
            new_name='capital_cas_branch__e18717_idx',
            old_name='capital_cashbob_branch_fecha_idx',
        ),
        migrations.AlterUniqueTogether(
            name='cashbob',
            unique_together={('branch', 'fecha')},
        ),
    ]
