# Generated by Django 4.2.16 on 2026-05-01 16:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0009_add_currency_position'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='currencyposition',
            new_name='capital_cur_branch__0b8643_idx',
            old_name='cap_pos_branch_cur_idx',
        ),
        migrations.RenameIndex(
            model_name='currencypositionhistory',
            new_name='capital_cur_positio_e489a7_idx',
            old_name='cap_pos_hist_pos_fecha_idx',
        ),
        migrations.AlterField(
            model_name='currencyposition',
            name='avg_acquisition_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Costo promedio de adquisición en BOB (WAC).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='currencyposition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='currencyposition',
            name='net_position',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Posición neta en unidades de la divisa (+ = largo, - = corto).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='currencyposition',
            name='total_cost_bob',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Costo total acumulado en BOB (para calcular WAC).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='currencyposition',
            name='unrealized_pnl_official',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='P&L no realizado valorizado a tasa oficial.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='currencyposition',
            name='unrealized_pnl_parallel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='P&L no realizado valorizado a tasa paralela.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='currencypositionhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
