# Generated by Django 4.2.16 on 2026-05-02 14:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital', '0010_rename_cap_pos_branch_cur_idx_capital_cur_branch__0b8643_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currencyposition',
            name='official_rate_used',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Alias histórico — almacena la tasa paralela usada (BCB eliminado).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='currencyposition',
            name='unrealized_pnl_official',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='P&L no realizado valorizado a tasa paralela (alias histórico, igual a unrealized_pnl_parallel).', max_digits=18),
        ),
        migrations.AlterField(
            model_name='currencypositionhistory',
            name='official_rate',
            field=models.DecimalField(decimal_places=4, help_text='Alias histórico — almacena la tasa paralela (BCB eliminado).', max_digits=10, null=True),
        ),
    ]
