# Generated by Django 4.2.30 on 2026-07-11 02:40

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_users_branch_company_active_idx_users_branc_company_058b1d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('capital', '0011_alter_currencyposition_official_rate_used_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('tipo', models.CharField(help_text='Concepto libre: Venta indirecta, Caiditas, Comisión, Interés, etc.', max_length=50)),
                ('monto_bob', models.DecimalField(decimal_places=2, help_text='Monto del ingreso en BOB', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('QR', 'QR / Billetera digital'), ('TRANSFER', 'Transferencia bancaria'), ('TARJETA', 'Tarjeta de débito/crédito')], default='EFECTIVO', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_extra', to='users.branch')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ingreso Extra',
                'verbose_name_plural': 'Ingresos Extra',
                'db_table': 'capital_ingreso_extra',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['-fecha'], name='capital_ing_fecha_e83f25_idx'), models.Index(fields=['branch', '-fecha'], name='capital_ing_branch__ebe420_idx')],
            },
        ),
    ]
