# Generated by Django 4.2.16 on 2026-03-25 01:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('digital_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=15)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=Decimal('1000'), max_digits=15)),
                ('maximum_stock', models.DecimalField(decimal_places=2, default=Decimal('50000'), max_digits=15)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=Decimal('2000'), max_digits=15)),
                ('weighted_average_cost', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('last_recount', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventario de Divisa',
                'verbose_name_plural': 'Inventarios de Divisas',
            },
        ),
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Stock Bajo'), ('OVERSTOCK', 'Exceso de Stock'), ('SIGNIFICANT_ADJUSTMENT', 'Ajuste Significativo'), ('TRANSFER_PENDING', 'Transferencia Pendiente'), ('RECOUNT_NEEDED', 'Reconteo Necesario')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=10)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alerta de Inventario',
                'verbose_name_plural': 'Alertas de Inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida'), ('ADJUSTMENT', 'Ajuste'), ('TRANSFER_IN', 'Transferencia Entrada'), ('TRANSFER_OUT', 'Transferencia Salida')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_TRANSIT', 'En Tránsito'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Transferencia de Inventario',
                'verbose_name_plural': 'Transferencias de Inventario',
                'ordering': ['-created_at'],
            },
        ),
    ]
