# Generated by Django 4.2.16 on 2026-03-25 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransfer',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_authorized', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rates.currency'),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='requested_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='source_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_sent', to='users.branch'),
        ),
        migrations.AddField(
            model_name='inventorytransfer',
            name='target_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received', to='users.branch'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.currencyinventory'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryalert',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='inventory.currencyinventory'),
        ),
        migrations.AddField(
            model_name='inventoryalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryalert',
            name='triggered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencyinventory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='users.branch'),
        ),
        migrations.AddField(
            model_name='currencyinventory',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='rates.currency'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['inventory', '-created_at'], name='inventory_i_invento_e0d526_idx'),
        ),
        migrations.AddIndex(
            model_name='inventorymovement',
            index=models.Index(fields=['movement_type', '-created_at'], name='inventory_i_movemen_979428_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['is_resolved', '-created_at'], name='inventory_i_is_reso_08b4eb_idx'),
        ),
        migrations.AddIndex(
            model_name='inventoryalert',
            index=models.Index(fields=['alert_type', '-created_at'], name='inventory_i_alert_t_1212f6_idx'),
        ),
        migrations.AddIndex(
            model_name='currencyinventory',
            index=models.Index(fields=['currency', 'branch'], name='inventory_c_currenc_a325ea_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='currencyinventory',
            unique_together={('currency', 'branch')},
        ),
    ]
