# Generated by Django 4.2.16 on 2026-04-14 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0003_alter_inventorymovement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryalert_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventoryalert',
            name='triggered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventoryalert_triggered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventorytransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_received_by_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
