# Generated by Django 4.2.16 on 2026-04-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_fix_related_name_conflicts'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('INACTIVE', 'Inactiva'), ('BLOCKED', 'Bloqueada')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarjeta de Inventario',
                'verbose_name_plural': 'Tarjetas de Inventario',
                'ordering': ['-created_at'],
            },
        ),
    ]
