# Generated by Django 4.2.30 on 2026-07-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_migration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='migrationlog',
            name='target_model',
            field=models.CharField(choices=[('transactions', 'Transacciones'), ('rates', 'Tasas de cambio'), ('customers', 'Clientes'), ('capital', 'Capital / Gastos')], db_index=True, max_length=50),
        ),
    ]
