# Generated by Django 4.2.16 on 2026-03-25 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Divisa',
                'verbose_name_plural': 'Divisas',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='RateConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_margin_morning', models.DecimalField(decimal_places=2, help_text='Margen de compra en la mañana (%)', max_digits=5)),
                ('sell_margin_morning', models.DecimalField(decimal_places=2, help_text='Margen de venta en la mañana (%)', max_digits=5)),
                ('buy_margin_afternoon', models.DecimalField(decimal_places=2, help_text='Margen de compra en la tarde (%)', max_digits=5)),
                ('sell_margin_afternoon', models.DecimalField(decimal_places=2, help_text='Margen de venta en la tarde (%)', max_digits=5)),
                ('buy_margin_evening', models.DecimalField(decimal_places=2, help_text='Margen de compra en la noche (%)', max_digits=5)),
                ('sell_margin_evening', models.DecimalField(decimal_places=2, help_text='Margen de venta en la noche (%)', max_digits=5)),
                ('min_transaction_amount', models.DecimalField(decimal_places=2, default=10, max_digits=10)),
                ('max_transaction_amount', models.DecimalField(decimal_places=2, default=10000, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_from', to='rates.currency')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_to', to='rates.currency')),
            ],
            options={
                'verbose_name': 'Configuración de Tasa',
                'verbose_name_plural': 'Configuraciones de Tasas',
                'unique_together': {('currency_from', 'currency_to')},
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('buy_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sell_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('source', models.CharField(default='BCB', max_length=50)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='rates.currency')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='rates.currency')),
            ],
            options={
                'ordering': ['-valid_from'],
                'indexes': [models.Index(fields=['currency_from', 'currency_to', '-valid_from'], name='rates_excha_currenc_2f75d7_idx')],
                'unique_together': {('currency_from', 'currency_to', 'valid_from')},
            },
        ),
    ]
