# Generated by Django 4.2.16 on 2026-04-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exchangerate',
            name='market_type',
            field=models.CharField(choices=[('official', 'Oficial'), ('parallel', 'Paralelo')], db_index=True, default='official', help_text='Oficial: tasa BCB regulada. Paralelo: mercado negro/negro paralelo.', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('currency_from', 'currency_to', 'valid_from', 'market_type')},
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['market_type', 'currency_from', 'currency_to'], name='rates_excha_market__da3c8a_idx'),
        ),
    ]
