# Generated by Django 4.2.16 on 2026-04-08 02:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_add_exchange_rate_source'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exchangerate',
            new_name='rates_excha_rate_so_5b2522_idx',
            old_name='rates_excha_rate_so_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangerate',
            new_name='rates_excha_valid_u_635559_idx',
            old_name='rates_excha_valid_u_idx',
        ),
        migrations.AlterField(
            model_name='exchangeratesource',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Peso en el cálculo de tasa promedio ponderada (paralelo>digital>oficial)', max_digits=4),
        ),
    ]
