# Generated by Django 4.2.16 on 2026-04-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0005_rename_rates_excha_rate_so_idx_rates_excha_rate_so_5b2522_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='market_type',
            field=models.CharField(choices=[('official', 'Oficial BCB'), ('bcb', 'BCB Referencial'), ('paralelo_digital', 'Paralelo Digital (Binance/Takenos/Airtm)'), ('paralelo_fisico_empresa', 'Paralelo Físico — Empresa'), ('paralelo_fisico_competencia', 'Paralelo Físico — Competencia'), ('parallel', 'Mercado Paralelo (legacy)'), ('digital', 'Plataforma Digital (legacy)')], db_index=True, default='official', help_text='Tipo de mercado que representa esta tasa.', max_length=30),
        ),
    ]
