# Generated by Django 4.2.16 on 2026-04-11 14:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0007_add_pricing_decision_log'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exchangeratedecisionlog',
            new_name='rates_prici_currenc_95f50a_idx',
            old_name='rates_pricin_curr_cd_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangeratedecisionlog',
            new_name='rates_prici_branch__6fd276_idx',
            old_name='rates_pricin_branch_idx',
        ),
        migrations.AlterField(
            model_name='exchangeratedecisionlog',
            name='demand_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Factor de ajuste por demanda reciente', max_digits=7),
        ),
        migrations.AlterField(
            model_name='exchangeratedecisionlog',
            name='inventory_factor',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Factor de ajuste por nivel de inventario', max_digits=7),
        ),
        migrations.AlterField(
            model_name='exchangeratedecisionlog',
            name='inventory_stock_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Stock como % del máximo', max_digits=6, null=True),
        ),
    ]
