# Generated by Django 4.2.16 on 2026-04-18 02:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0010_add_is_primary_avg_rate'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='exchangerate',
            name='rates_excha_is_prim_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangerate',
            new_name='rates_excha_source__7dff22_idx',
            old_name='rates_excha_src_mth_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangerate',
            new_name='rates_excha_is_vali_8722e6_idx',
            old_name='rates_excha_validated_idx',
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='confidence',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Confianza 0.000–1.000 heredada del fetcher (0.5=hardcoded, 0.95=API directa).', max_digits=4),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False, help_text='True para la tasa que el sistema usará en todas las transacciones. Solo puede haber una tasa primaria activa por par de divisas. Seleccionada automáticamente por ExchangeRateService basado en confianza, fuente y tipo de mercado.'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='source',
            field=models.CharField(default='BCB', help_text='Nombre(s) de la fuente — legado, usar source_method para clasificación.', max_length=50),
        ),
    ]
