# Generated by Django 4.2.16 on 2026-04-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0012_currency_internationalization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='scale_factor',
            field=models.IntegerField(default=1, help_text='Multiplicador de unidades. scale_factor=1000 → tasa cotizada por 1000 unidades reales (ej. CLP, ARS). scale_factor=1 → tasa por unidad (ej. USD, EUR).'),
        ),
    ]
