# Generated by Django 4.2.16 on 2026-04-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0014_exchangeratesnapshot_seed_currencies'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exchangeratesnapshot',
            new_name='rates_excha_date_683479_idx',
            old_name='rates_snap_date_idx',
        ),
        migrations.RenameIndex(
            model_name='exchangeratesnapshot',
            new_name='rates_excha_status_c02460_idx',
            old_name='rates_snap_status_date_idx',
        ),
        migrations.AlterField(
            model_name='exchangeratesnapshot',
            name='aggregated_data',
            field=models.JSONField(default=dict, help_text='Mapa {currency_code: {buy, sell, avg, spread_pct, confidence, sources[], market_type, source_method}} para cada divisa activa.'),
        ),
        migrations.AlterField(
            model_name='exchangeratesnapshot',
            name='anomaly_count',
            field=models.IntegerField(default=0, help_text='Número de anomalías de precio detectadas durante el día.'),
        ),
        migrations.AlterField(
            model_name='exchangeratesnapshot',
            name='avg_usd_buy',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Promedio de compra USD/BOB del día.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='exchangeratesnapshot',
            name='avg_usd_sell',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Promedio de venta USD/BOB del día.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='exchangeratesnapshot',
            name='best_source',
            field=models.CharField(blank=True, help_text='Fuente más confiable del día (binance/dolarblue/bcb/manual).', max_length=50),
        ),
        migrations.AlterField(
            model_name='exchangeratesnapshot',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exchangeratesnapshot',
            name='max_spread_pct',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Spread máximo registrado durante el día (%).', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='exchangeratesnapshot',
            name='source_count',
            field=models.IntegerField(default=0, help_text='Número de fuentes activas que reportaron en este snapshot.'),
        ),
    ]
