# Generated by Django 4.2.16 on 2026-05-01 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0016_referencerate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='referencerate',
            new_name='rates_refer_currenc_904c1f_idx',
            old_name='rates_ref_currency_source_ts_idx',
        ),
    ]
