# Generated by Django 4.2.16 on 2026-05-02 14:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0018_remove_bcb_official_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeratedecisionlog',
            name='weight_binance',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.45'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='exchangeratedecisionlog',
            name='weight_competition',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.20'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='exchangeratedecisionlog',
            name='weight_historical',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.35'), max_digits=5),
        ),
    ]
