# Generated by Django 4.2.16 on 2026-05-05 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0020_add_raw_consensus_integration_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerateconsensus',
            name='cambio_pct_24h',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Variación vs consenso de hace 24h (%)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='exchangerateconsensus',
            name='confianza_pct',
            field=models.IntegerField(default=0, help_text='0-100: % de confianza del consenso'),
        ),
        migrations.AlterField(
            model_name='exchangerateconsensus',
            name='fuentes_usadas',
            field=models.JSONField(default=list, help_text='[{id_fuente, peso, precio_compra, precio_venta}]'),
        ),
        migrations.AlterField(
            model_name='exchangerateconsensus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exchangerateconsensus',
            name='par',
            field=models.CharField(db_index=True, help_text='ej: USD/BOB', max_length=7),
        ),
        migrations.AlterField(
            model_name='exchangerateconsensus',
            name='tendencia',
            field=models.CharField(blank=True, help_text='ALCISTA | BAJISTA | NEUTRAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='exchangerateconsensus',
            name='vigente',
            field=models.BooleanField(db_index=True, default=False, help_text='Solo True para el consenso activo por par'),
        ),
        migrations.AlterField(
            model_name='exchangerateraw',
            name='fuente',
            field=models.ForeignKey(blank=True, help_text='Fuente que generó este dato (null si fuente eliminada)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='raw_rates', to='rates.exchangeratesource'),
        ),
        migrations.AlterField(
            model_name='exchangerateraw',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='exchangerateraw',
            name='id_fuente_str',
            field=models.CharField(db_index=True, help_text='Copia de id_fuente para búsquedas rápidas sin JOIN', max_length=60),
        ),
        migrations.AlterField(
            model_name='exchangerateraw',
            name='payload_raw',
            field=models.JSONField(default=dict, help_text='JSON original completo — activo de ML'),
        ),
        migrations.AlterField(
            model_name='exchangerateraw',
            name='timestamp_fuente',
            field=models.DateTimeField(help_text='Momento en que la fuente dice que es el dato (puede ser aproximado)'),
        ),
        migrations.AlterField(
            model_name='exchangeratesource',
            name='pais_referencia',
            field=models.CharField(blank=True, help_text='Código ISO 3166-1 alpha-2 (BO, AR, BR…)', max_length=3),
        ),
    ]
