# Generated by Django 4.2.30 on 2026-07-14 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0022_rawratesnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='market_type',
            field=models.CharField(choices=[('official', 'Oficial (BCB)'), ('paralelo_digital', 'Paralelo Digital (Binance/Takenos/Airtm)'), ('paralelo_fisico_empresa', 'Paralelo Físico — Empresa'), ('paralelo_fisico_competencia', 'Paralelo Físico — Competencia'), ('parallel', 'Mercado Paralelo (legacy)'), ('digital', 'Plataforma Digital (legacy)')], db_index=True, default='paralelo_digital', help_text='Tipo de mercado que representa esta tasa.', max_length=30),
        ),
        migrations.AlterField(
            model_name='rawratesnapshot',
            name='source',
            field=models.CharField(choices=[('binance_p2p', 'Binance P2P'), ('dolar_blue_bolivia', 'DolarBlueBolivia'), ('airtm', 'AirTM'), ('eldorado', 'Eldorado'), ('wallbit', 'Wallbit'), ('saldoar', 'SaldoAR'), ('okx', 'OKX P2P'), ('p2p_exchanges', 'P2P Exchanges'), ('bitget_p2p', 'Bitget P2P'), ('bybit_p2p', 'Bybit P2P'), ('p2p_multi_fiat', 'P2P Multi-Fiat'), ('digital', 'Digital (Takenos/Airtm)'), ('parallel', 'Parallel Scraper'), ('dolarapi', 'DolarAPI'), ('criptoya', 'Criptoya'), ('other', 'Other')], db_index=True, max_length=30),
        ),
    ]
