# Generated by Django 4.2.16 on 2026-04-07 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactiondocument',
            options={'verbose_name': 'Documento de Transacción', 'verbose_name_plural': 'Documentos de Transacción'},
        ),
    ]
