# Generated by Django 4.2.16 on 2026-04-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_add_transaction_category_nullable_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='carnet_identidad',
            field=models.CharField(blank=True, db_index=True, help_text='Número de CI/documento (desnormalizado de customer.document_number). Requerido para transacciones REPORTABLE.', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='nombre_cliente',
            field=models.CharField(blank=True, help_text='Nombre completo del cliente (desnormalizado de customer.full_name).', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='visible_asfi',
            field=models.BooleanField(db_index=True, default=True, help_text='Si TRUE, la transacción aparece en los reportes regulatorios ASFI (RTE, Libro Diario).  Se establece automáticamente según transaction_category: REPORTABLE → True, INTERNA → False.  Puede sobreescribirse manualmente en casos excepcionales.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='is_reportable_to_asfi',
            field=models.BooleanField(db_index=True, default=True, help_text='Alias de visible_asfi. Mantenido para compatibilidad con reportes ASFI.'),
        ),
    ]
