# Generated by Django 4.2.16 on 2026-04-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_add_company_to_customer'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='transaction_documen_4ed5c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='transaction_full_na_904a87_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='transaction_company_64ccab_idx',
            old_name='tx_customer_company_doc_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='transaction_company_4cb591_idx',
            old_name='tx_customer_company_name_idx',
        ),
    ]
