# Generated by Django 4.2.16 on 2026-04-30 20:53

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0015_add_fraud_rule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'permissions': [('can_reverse_transaction', 'Puede revertir transacciones'), ('can_view_all_branches', 'Puede ver transacciones de todas las sucursales'), ('can_approve_high_value', 'Puede aprobar transacciones de alto valor'), ('can_override_fraud_flag', 'Puede anular flags de fraude'), ('can_view_audit_trail', 'Puede ver el trail de auditoría'), ('can_manual_rate', 'Puede aplicar tasa manual (con justificación)')], 'verbose_name': 'Transacción', 'verbose_name_plural': 'Transacciones'},
        ),
        migrations.RenameIndex(
            model_name='transactionauditlog',
            new_name='transaction_transac_c8e212_idx',
            old_name='tx_audit_tx_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionauditlog',
            new_name='transaction_action_b9a1b7_idx',
            old_name='tx_audit_action_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionauditlog',
            new_name='transaction_user_id_5c2900_idx',
            old_name='tx_audit_user_ts_idx',
        ),
        migrations.AlterField(
            model_name='fraudrule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='fraudrule',
            name='score_delta',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.3000'), help_text='Cuánto suma esta regla al fraud_score (0–1).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='fraudrule',
            name='threshold',
            field=models.DecimalField(decimal_places=4, help_text='VELOCITY: max transacciones/hora; AMOUNT_ANOMALY: número de σ; RATE_SANITY: % desviación máxima; DUPLICATE: ventana en minutos; HIGH_VALUE: monto mínimo en BOB para disparar.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='approval_required',
            field=models.BooleanField(db_index=True, default=False, help_text='True si FraudDetectionEngine requirió aprobación manual.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Usuario que aprobó la transacción tras revisión antifraude.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fraud_flags',
            field=models.JSONField(blank=True, default=list, help_text='Lista de reglas antifraude disparadas en esta transacción.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fraud_score',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Score de riesgo calculado por FraudDetectionEngine (0.0000–1.0000).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='manual_rate_justification',
            field=models.TextField(blank=True, help_text='Justificación obligatoria cuando se usa tasa manual (CAN_MANUAL_RATE).'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='parallel_rate_at_creation',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Tasa paralela de mercado en el momento de creación (snapshot inmutable).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='rate_lock_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp hasta el que la tasa de la transacción está bloqueada.', null=True),
        ),
        migrations.AlterField(
            model_name='transactionauditlog',
            name='checksum_sha256',
            field=models.CharField(help_text='SHA-256 del contenido del registro para detectar manipulación.', max_length=64),
        ),
        migrations.AlterField(
            model_name='transactionauditlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transactionauditlog',
            name='new_state',
            field=models.JSONField(default=dict, help_text='Estado de los campos relevantes DESPUÉS de la acción.'),
        ),
        migrations.AlterField(
            model_name='transactionauditlog',
            name='previous_state',
            field=models.JSONField(default=dict, help_text='Estado de los campos relevantes ANTES de la acción.'),
        ),
        migrations.AlterField(
            model_name='transactionauditlog',
            name='transaction_number',
            field=models.CharField(db_index=True, help_text='Desnormalizado para búsqueda rápida sin JOIN.', max_length=20),
        ),
        migrations.AlterField(
            model_name='transactionauditlog',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Usuario que ejecutó la acción (null = sistema/Celery).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transactionauditlog',
            name='user_display',
            field=models.CharField(blank=True, help_text='Username desnormalizado para auditoría offline.', max_length=200),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', '-created_at'], name='transaction_status_4b1739_idx'),
        ),
    ]
