# Generated by Django 4.2.16 on 2026-04-07 23:50

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_alter_branch_options_alter_user_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVentaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.PositiveIntegerField()),
                ('costo_unitario', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
            options={
                'verbose_name': 'Detalle Venta-Lote',
                'db_table': 'tarjetas_detalle_venta_lote',
            },
        ),
        migrations.CreateModel(
            name='LoteCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(default='Proveedor', max_length=200)),
                ('cantidad_total', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cantidad_restante', models.PositiveIntegerField()),
                ('precio_costo', models.DecimalField(decimal_places=4, help_text='Precio de costo por tarjeta en BOB', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('numero_factura', models.CharField(blank=True, max_length=50)),
                ('fecha_compra', models.DateField(default=django.utils.timezone.localdate)),
                ('is_active', models.BooleanField(default=True)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Lote de Compra',
                'verbose_name_plural': 'Lotes de Compra',
                'db_table': 'tarjetas_lote',
                'ordering': ['fecha_compra', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operadora', models.CharField(choices=[('TIGO', 'Tigo'), ('VIVA', 'Viva'), ('CLARO', 'Claro'), ('ENTEL', 'Entel'), ('OTRA', 'Otra')], max_length=10)),
                ('nombre', models.CharField(help_text='Ej: Tigo 5 BOB', max_length=100)),
                ('denominacion', models.DecimalField(decimal_places=2, help_text='Valor nominal en BOB', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('descripcion', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Tarjeta',
                'verbose_name_plural': 'Tipos de Tarjeta',
                'db_table': 'tarjetas_tipo',
                'ordering': ['operadora', 'denominacion'],
            },
        ),
        migrations.CreateModel(
            name='VentaTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venta', models.CharField(editable=False, max_length=20, unique=True)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_venta', models.DecimalField(decimal_places=2, help_text='Precio de venta por tarjeta en BOB', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('total_bob', models.DecimalField(decimal_places=2, help_text='total = precio_venta × cantidad', max_digits=15)),
                ('costo_fifo_bob', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Costo real de las unidades vendidas (FIFO)', max_digits=15)),
                ('ganancia_bob', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Ganancia neta = total_bob - costo_fifo_bob', max_digits=15)),
                ('medio_pago', models.CharField(choices=[('CASH', 'Efectivo'), ('QR', 'QR'), ('TRANSFER', 'Transferencia')], default='CASH', max_length=10)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200)),
                ('cliente_tel', models.CharField(blank=True, max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_tarjetas', to='users.branch')),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_tarjetas', to=settings.AUTH_USER_MODEL)),
                ('tipo_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='tarjetas.tipotarjeta')),
            ],
            options={
                'verbose_name': 'Venta de Tarjeta',
                'verbose_name_plural': 'Ventas de Tarjetas',
                'db_table': 'tarjetas_venta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tipotarjeta',
            index=models.Index(fields=['operadora', 'is_active'], name='tarjetas_ti_operado_b610d6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tipotarjeta',
            unique_together={('operadora', 'denominacion')},
        ),
        migrations.AddField(
            model_name='lotecompra',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lotecompra',
            name='tipo_tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='tarjetas.tipotarjeta'),
        ),
        migrations.AddField(
            model_name='detalleventalote',
            name='lote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='tarjetas.lotecompra'),
        ),
        migrations.AddField(
            model_name='detalleventalote',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_lote', to='tarjetas.ventatarjeta'),
        ),
        migrations.AddIndex(
            model_name='ventatarjeta',
            index=models.Index(fields=['-created_at'], name='tarjetas_ve_created_c1011a_idx'),
        ),
        migrations.AddIndex(
            model_name='ventatarjeta',
            index=models.Index(fields=['tipo_tarjeta', '-created_at'], name='tarjetas_ve_tipo_ta_019fb8_idx'),
        ),
        migrations.AddIndex(
            model_name='ventatarjeta',
            index=models.Index(fields=['cajero', '-created_at'], name='tarjetas_ve_cajero__b80e90_idx'),
        ),
        migrations.AddIndex(
            model_name='lotecompra',
            index=models.Index(fields=['tipo_tarjeta', 'is_active', 'fecha_compra'], name='tarjetas_lo_tipo_ta_ced3fd_idx'),
        ),
    ]
