# Generated by Django 4.2.16 on 2026-04-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0003_add_movimiento_tarjeta'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='movimientotarjeta',
            new_name='tarjetas_mo_tipo_ta_644f8c_idx',
            old_name='tarjetas_mov_tipo_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientotarjeta',
            new_name='tarjetas_mo_tipo_mo_588689_idx',
            old_name='tarjetas_mov_tipmov_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientotarjeta',
            new_name='tarjetas_mo_branch__5941d4_idx',
            old_name='tarjetas_mov_branch_ts_idx',
        ),
        migrations.AlterField(
            model_name='movimientotarjeta',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
