# Generated by Django 4.2.16 on 2026-05-06 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_users_branch_company_active_idx_users_branc_company_058b1d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tarjetas', '0004_rename_tarjetas_mov_tipo_ts_idx_tarjetas_mo_tipo_ta_644f8c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventatarjeta',
            name='anulado_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventatarjeta',
            name='anulado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_anuladas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ventatarjeta',
            name='estado',
            field=models.CharField(choices=[('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], db_index=True, default='COMPLETADA', max_length=10),
        ),
        migrations.AddField(
            model_name='ventatarjeta',
            name='motivo_anulacion',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AlertaInventarioTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_minimo', models.PositiveIntegerField(default=20, help_text='Stock mínimo antes de warning (amarillo)')),
                ('stock_critico', models.PositiveIntegerField(default=5, help_text='Stock crítico — alerta roja')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, help_text='Dejar vacío para aplicar globalmente a todas las sucursales', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas_tarjetas', to='users.branch')),
                ('tipo_tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_inventario', to='tarjetas.tipotarjeta')),
            ],
            options={
                'verbose_name': 'Alerta de Inventario',
                'verbose_name_plural': 'Alertas de Inventario',
                'db_table': 'tarjetas_alerta_inventario',
                'indexes': [models.Index(fields=['tipo_tarjeta', 'is_active'], name='tarjetas_al_tipo_ta_ad0ceb_idx')],
                'unique_together': {('tipo_tarjeta', 'branch')},
            },
        ),
    ]
