# Generated by Django 4.2.16 on 2026-07-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarjetas', '0006_tipotarjeta_company_multitenant'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tipotarjeta',
            new_name='tarjetas_ti_company_5b0256_idx',
            old_name='tarjetas_ti_company_9f3a1c_idx',
        ),
    ]
