# Generated by Django 4.2.16 on 2026-04-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_audit_log'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_ct_obj_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_user_ts_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='audit_action_ts_idx',
        ),
    ]
