# Generated by Django 4.2.16 on 2026-04-28 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_company_to_branch_user'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='branch',
            new_name='users_branc_company_058b1d_idx',
            old_name='users_branch_company_active_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_user_company_9b5f6c_idx',
            old_name='users_user_company_role_idx',
        ),
        migrations.AlterField(
            model_name='branch',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Principal / matriz'),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
